### ISSUE TITLE
No responsiveness

### ISSUE THREAD

**Issue by spiderhands** [JSConfArmenia/conf-19#2]
Hi guys! First of all thank you for your work for our community!

I have some issues with site responsiveness and load speeds. 

Here you can check out some metrics from Google and GTmetrix:

- https://developers.google.com/speed/pagespeed/insights/?url=jsconf.am&tab=desktop

- https://gtmetrix.com/reports/jsconf.am/6eoVW2ht

- Also lighthouse shows not best results.

Is there any way that i can help you with this? Will you accept PRs outside of your team? Can you share any design related materials?

**Comment by nairihar** [comment]
Hi @spiderhands, sure, if you can improve the existing code base and speed up the website loading speed, then go ahead and open a PR :) 

cc @varszakaryan @modularcoder

**Comment by varszakaryan** [comment]
Thanks for your care! 🇦🇲
